export const products = [
  {
    _id: "1",
    product_name: "Handmade Ceramic Mug",
    product_image: "https://placehold.co/400x400?text=Mug",
    product_description: "A cozy hand-thrown mug, glazed in matte white.",
    price: 25,
    category: "Pottery",
  },
  {
    _id: "2",
    product_name: "Woven Wool Throw",
    product_image: "https://placehold.co/400x400?text=Throw",
    product_description: "Hand-loomed wool blanket, natural undyed fibers.",
    price: 68,
    category: "Textiles",
  },
  {
    _id: "3",
    product_name: "Carved Oak Spoon",
    product_image: "https://placehold.co/400x400?text=Spoon",
    product_description: "A single-piece carved serving spoon, food-safe oil finish.",
    price: 18,
    category: "Woodwork",
  },
  {
    _id: "4",
    product_name: "Hand-Blown Glass Vase",
    product_image: "https://placehold.co/400x400?text=Vase",
    product_description: "Small bud vase, blown and shaped by hand.",
    price: 42,
    category: "Glasswork",
  },
  {
    _id: "5",
    product_name: "Stoneware Serving Bowl",
    product_image: "https://placehold.co/400x400?text=Bowl",
    product_description: "Wheel-thrown stoneware bowl with a speckled glaze finish.",
    price: 34,
    category: "Pottery",
  },
  {
    _id: "6",
    product_name: "Macrame Wall Hanging",
    product_image: "https://placehold.co/400x400?text=Macrame",
    product_description: "Hand-knotted cotton cord wall art, natural cream tone.",
    price: 52,
    category: "Textiles",
  },
  {
    _id: "7",
    product_name: "Walnut Cutting Board",
    product_image: "https://placehold.co/400x400?text=Board",
    product_description: "End-grain walnut board, hand-sanded and oiled.",
    price: 45,
    category: "Woodwork",
  },
  {
    _id: "8",
    product_name: "Amber Glass Candle Holder",
    product_image: "https://placehold.co/400x400?text=Candle+Holder",
    product_description: "Hand-blown amber glass, holds a single taper candle.",
    price: 22,
    category: "Glasswork",
  },
];